- name: 'Execute command on host'
  hosts: 127.0.0.1
  connection: local
  tasks:
   - name: Execute command on host
     command: echo {{ arg }}
     register: output
   - name: Print out put of previous task
     debug:
       msg: " {{ output.stdout }} "
